#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=00:05:00

set -e
set -x

masks=`jq -r '.masks' config.json`
box_size_max=`jq -r '.box_size_max' config.json`

mkdir -p csv

#creating mask name list
ls $masks > mask_name_list.txt #automatically create mask_name_list
sed -i '/json/d' tract_name_list.txt #remove json files if any
#sed -e s/.nii.gz//g -i tract_name_list.txt #remove suffix .nii.gz
#sed -e s/_Vol//g -i tract_name_list.txt #remove suffix _Vol if any

echo "Computing fractal dimension..."
singularity exec -e docker://brainlife/dipy:0.16.0 python run.py -masks $masks -box_size_max $box_size_max

if [ -z "$(ls -A -- "csv")" ]; then    
	echo "Computation failed."; 
	exit 1;
else    
	echo "Computation done." 
fi
